"""Update post model

Revision ID: 3eb08ed0b261
Revises: f88695eaa63a
Create Date: 2021-05-01 17:57:15.434461

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eb08ed0b261'
down_revision = 'f88695eaa63a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('posts_category_id_fkey', 'posts', type_='foreignkey')
    op.drop_column('posts', 'category_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('posts_category_id_fkey', 'posts', 'category', ['category_id'], ['id'])
    # ### end Alembic commands ###
